name: cd

on:
  workflow_dispatch:
  push:
    branches:
      - develop
    paths:
      - 'src/*'
      - '.github/workflows/CD.yml'

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pages:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@master
        with:
          repository: gamelly/gly-engine
          ref: develop
      - 
        uses: actions/checkout@master
        with:
          path: game
      - 
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: '5.4'
      -
        run: |
          docker run --rm -v $(pwd):/app -w /app/game/src haxe:4.3.6-bullseye haxe Game.hx --lua /app/haxe/game.lua
      - 
        run: |
          sudo chmod 666 haxe/game.lua
      - 
        run: |
          ./cli.sh tool-haxe-build haxe/game.lua
      - 
        run: |
          ./cli.sh build --core html5 haxe/game.lua
      -
        uses: actions/configure-pages@v3
      -
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'
      -
        id: deployment
        uses: actions/deploy-pages@v2
